afl_path: '/home/sefcom/AFLplusplus/afl-fuzz'
strace_output: '/tmp/strace_output.txt'
debug_mode: 'Line'

fuzz:
  fuzz_folder: '/home/sefcom/TestBinaries/fuzzing_xpdf'
  inputs: 'inputs/'
  binary: 'pdftotext'

bench:
  output_file: 'results.txt'
  time: 120
  iterations: 2
  xpdf:
    bin_path: '/home/sefcom/TestBinaries/fuzzing_xpdf/pdftotext'
    base_path: '/home/sefcom/TestBinaries/fuzzing_xpdf/outputs/base'
    output_path: '/home/sefcom/TestBinaries/fuzzing_xpdf/outputs'
    input_path: '/home/sefcom/TestBinaries/fuzzing_xpdf/inputs'
  sleep:
    bin_path: '/home/sefcom/TestBinaries/fuzzing_sleep/sleep'
    base_path: '/home/sefcom/TestBinaries/fuzzing_sleep/outputs/base'
    output_path: '/home/sefcom/TestBinaries/fuzzing_sleep/outputs'
    input_path: '/home/sefcom/TestBinaries/fuzzing_sleep/inputs'
  objdump:
    bin_path: '/home/sefcom/TestBinaries/fuzzing_objdump/objdump'
    base_path: '/home/sefcom/TestBinaries/fuzzing_objdump/outputs/base'
    output_path: '/home/sefcom/TestBinaries/fuzzing_objdump/outputs'
    input_path: '/home/sefcom/TestBinaries/fuzzing_objdump/inputs'

gdb:
  #breakpoints: ['afl-fuzz-bitmap.c:545']
  breakpoints: ['save_if_interesting']
  log_path: 'default/replay/check.txt'
  base_folder_path: 'outputs/unseed'
  replay_folder_path: 'outputs/line'
  replay:
    log_increment: 200
  line:
    line_stop: 988264
  seed:
    seed_comparator: 'SeedComparatorBase'
    target_path: 'outputs/unseed/target'
    max_distance: 150
  
