afl_path: '/home/denis/AFLplusplus/afl-fuzz'
debug_mode: 'Seed'

fuzz:
  fuzz_folder: '/home/denis/Thesis/fuzzing_xpdf'
  inputs: 'pdf_examples'
  binary: 'install/bin/pdftotext'

gdb:
  breakpoints: ['afl-fuzz-bitmap.c:545']
  log_path: 'default/replay/check.txt'
  base_folder_path: 'outputs/unseed'
  replay_folder_path: 'outputs/replay'
  replay:
    log_increment: 200
  line:
    line_stop: 49500
  seed:
    seed_comparator: 'SeedComparatorBase'
    target_path: 'outputs/unseed/target'
    min_distance: 150
  