afl_path: '/home/sefcom/AFLplusplus/afl-fuzz'
debug_mode: 'Line'

fuzz:
  fuzz_folder: '/home/sefcom/TestBinaries/fuzzing_xpdf'
  inputs: 'inputs/'
  binary: 'pdftotext'

bench:
  output_path: '/home/sefcom/TestBinaries/fuzzing_xpdf/outputs'
  base_folder_path: '/home/sefcom/TestBinaries/fuzzing_xpdf/outputs/base'
  output_file: 'results.txt'
  xpdf_path: ''
  sleep_path: ''
  objdump_path: ''

gdb:
  #breakpoints: ['afl-fuzz-bitmap.c:545']
  breakpoints: ['save_if_interesting']
  log_path: 'default/replay/check.txt'
  base_folder_path: 'outputs/unseed'
  replay_folder_path: 'outputs/line'
  replay:
    log_increment: 200
  line:
    line_stop: 988264
  seed:
    seed_comparator: 'SeedComparatorBase'
    target_path: 'outputs/unseed/target'
    max_distance: 150
  
