afl_path: '/home/denis/AFLplusplus/afl-fuzz'
debug_mode: 'Line'

fuzz:
  fuzz_folder: '/home/denis/Thesis/fuzzing_xpdf'
  inputs: 'pdf_examples'
  binary: 'install/bin/pdftotext'

bench:
  time: 15
  iterations: 2
  xpdf:
    bin_path: '/home/denis/Thesis/fuzzing_xpdf/xpdf-3.02/xpdf/pdftotext'
    output_path: '/home/denis/Thesis/fuzzing_xpdf/outputs'
    input_path: '/home/denis/Thesis/fuzzing_xpdf/pdf_examples'
  # sleep:
    # bin_path: '/home/denis/TestBinaries/fuzzing_sleep/sleep'
    # base_path: '/home/denis/TestBinaries/fuzzing_sleep/outputs/base'
    # output_path: '/home/denis/TestBinaries/fuzzing_sleep/outputs'
    # input_path: '/home/denis/TestBinaries/fuzzing_sleep/inputs'
  # objdump:
    # bin_path: '/home/denis/TestBinaries/fuzzing_objdump/objdump'
    # base_path: '/home/denis/TestBinaries/fuzzing_objdump/outputs/base'
    # output_path: '/home/denis/TestBinaries/fuzzing_objdump/outputs'
    # input_path: '/home/denis/TestBinaries/fuzzing_objdump/inputs'

gdb:
  #breakpoints: ['afl-fuzz-bitmap.c:545']
  breakpoints: ['save_if_interesting']
  log_path: 'default/replay/check.txt'
  base_folder_path: 'outputs/unseed'
  replay_folder_path: 'outputs/line'
  replay:
    log_increment: 200
  line:
    line_stop: 988264
  seed:
    seed_comparator: 'SeedComparatorBase'
    target_path: 'outputs/unseed/target'
    max_distance: 150
