afl_path: '/home/denis/AFLplusplus/afl-fuzz'
debug_mode: 'replay'

fuzz:
  fuzz_folder: '/home/denis/Thesis/fuzzing_xpdf'
  inputs: 'pdf_examples'
  binary: 'install/bin/pdftotext'

gdb:
  breakpoints: ['afl-fuzz-init.c:778']
  log_path: 'default/replay/check.txt'
  replay:
    log_increment: 200
    outputs:
      base_folder_path: 'outputs/unseed'
      replay_folder_path: 'outputs/replay'
  line:
    line_stop: 49500
    outputs:
      base_folder_path: 'outputs/unseed'
      replay_folder_path: 'outputs/line'
  seed:
    target_path: 'outputs/unseed/target'
    min_distance: 150
    outputs:
      base_folder_path: 'outputs/unseed'
      replay_folder_path: 'outputs/seed'
  